blueprint:
  name: Simple ZHA Light Controller - Aqara Opple switch 3 bands
  description: Control and dim lights with Aqara Opple switch 3 bands (WXCJKG13LM)
  domain: automation
  input:
    aqara_sw:
      name: Aqara switch
      description: Aqara switch to use
      selector:
        device:
          integration: zha
          manufacturer: LUMI

    light_top:
      name: Light
      description: The light to control with the top buttons
      selector:
        target:
          entity:
            domain: light

    light_middle:
      name: Light
      description: The light to control with the middle buttons
      selector:
        target:
          entity:
            domain: light

    light_bottom:
      name: Light
      description: The light to control with the bottom buttons
      selector:
        target:
          entity:
            domain: light

    1_double:
      name: Button 1 - double click
      description: (Optional) Action to run on triple click of button 1
      default: []
      selector:
        action: null
    1_triple:
      name: Button 1 - triple click
      description: (Optional) Action to run on triple click of button 1
      default: []
      selector:
        action: null

    2_double:
      name: Button 2 - double click
      description: (Optional) Action to run on triple click of button 2
      default: []
      selector:
        action: null
    2_triple:
      name: Button 2 - triple click
      description: (Optional) Action to run on triple click of button 2
      default: []
      selector:
        action: null

    3_double:
      name: Button 3 - double click
      description: (Optional) Action to run on triple click of button 3
      default: []
      selector:
        action: null
    3_triple:
      name: Button 3 - triple click
      description: (Optional) Action to run on triple click of button 3
      default: []
      selector:
        action: null

    4_double:
      name: Button 4 - double click
      description: (Optional) Action to run on triple click of button 4
      default: []
      selector:
        action: null
    4_triple:
      name: Button 4 - triple click
      description: (Optional) Action to run on triple click of button 4
      default: []
      selector:
        action: null

    5_double:
      name: Button 5 - double click
      description: (Optional) Action to run on triple click of button 5
      default: []
      selector:
        action: null
    5_triple:
      name: Button 5 - triple click
      description: (Optional) Action to run on triple click of button 5
      default: []
      selector:
        action: null

    6_double:
      name: Button 6 - double click
      description: (Optional) Action to run on triple click of button 6
      default: []
      selector:
        action: null
    6_triple:
      name: Button 6 - triple click
      description: (Optional) Action to run on triple click of button 6
      default: []
      selector:
        action: null


mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input "aqara_sw"
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
  - choose:

      ## Turn on upper lights
      - conditions:
          - "{{ command == '1_single' }}"
        sequence:
          - service: light.turn_on
            target: !input "light_top"

      ## Increase brightness for upper lights
      - conditions:
          - "{{ command == '1_long' }}"
        sequence:
          repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 10 }}"
            sequence:
              - service: light.turn_on
                target: !input "light_top"
                data:
                  transition: 1
                  brightness_step_pct: 10

      ## Turn off upper lights
      - conditions:
          - "{{ command == '2_single' }}"
        sequence:
          - service: light.turn_off
            target: !input "light_top"

      ## Decrease brightness for upper lights
      - conditions:
          - "{{ command == '2_long' }}"
        sequence:
          repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 10 }}"
            sequence:
              - service: light.turn_on
                target: !input "light_top"
                data:
                  transition: 1
                  brightness_step_pct: -10

      ## Turn on middle lights
      - conditions:
          - "{{ command == '3_single' }}"
        sequence:
          - service: light.turn_on
            target: !input "light_middle"

      ## Increase brightness for middle lights
      - conditions:
          - "{{ command == '3_long' }}"
        sequence:
          repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 10 }}"
            sequence:
              - service: light.turn_on
                target: !input "light_middle"
                data:
                  transition: 1
                  brightness_step_pct: 10

      ## Turn off middle lights
      - conditions:
          - "{{ command == '4_single' }}"
        sequence:
          - service: light.turn_off
            target: !input "light_middle"

      ## Decrease brightness for middle lights
      - conditions:
          - "{{ command == '4_long' }}"
        sequence:
          repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 10 }}"
            sequence:
              - service: light.turn_on
                target: !input "light_middle"
                data:
                  transition: 1
                  brightness_step_pct: -10

      ## Turn on bottom lights
      - conditions:
          - "{{ command == '5_single' }}"
        sequence:
          - service: light.turn_on
            target: !input "light_bottom"

      ## Increase brightness for bottom lights
      - conditions:
          - "{{ command == '5_long' }}"
        sequence:
          repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 10 }}"
            sequence:
              - service: light.turn_on
                target: !input "light_bottom"
                data:
                  transition: 1
                  brightness_step_pct: 10

      ## Turn off bottom lights
      - conditions:
          - "{{ command == '6_single' }}"
        sequence:
          - service: light.turn_off
            target: !input "light_bottom"

      ## Decrease brightness for bottom lights
      - conditions:
          - "{{ command == '6_long' }}"
        sequence:
          repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 10 }}"
            sequence:
              - service: light.turn_on
                target: !input "light_bottom"
                data:
                  transition: 1
                  brightness_step_pct: -10

      ## Optional manual configurations
      - conditions:
          - "{{ command == '1_double' }}"
        sequence: !input "1_double"
      - conditions:
          - "{{ command == '2_double' }}"
        sequence: !input "2_double"
      - conditions:
          - "{{ command == '3_double' }}"
        sequence: !input "3_double"
      - conditions:
          - "{{ command == '4_double' }}"
        sequence: !input "4_double"
      - conditions:
          - "{{ command == '5_double' }}"
        sequence: !input "5_double"
      - conditions:
          - "{{ command == '6_double' }}"
        sequence: !input "6_double"
      - conditions:
          - "{{ command == '1_triple' }}"
        sequence: !input "1_triple"
      - conditions:
          - "{{ command == '2_triple' }}"
        sequence: !input "2_triple"
      - conditions:
          - "{{ command == '3_triple' }}"
        sequence: !input "3_triple"
      - conditions:
          - "{{ command == '4_triple' }}"
        sequence: !input "4_triple"
      - conditions:
          - "{{ command == '5_triple' }}"
        sequence: !input "5_triple"
      - conditions:
          - "{{ command == '6_triple' }}"
        sequence: !input "6_triple"

